development: &development
 adapter: mysql2
 strict: false
 database: jira_tracker
 username: root
 host: localhost
 password:
 socket: /private/tmp/mysql.sock
production:
  adapter: postgresql
  database: jira_prod
test:
  adapter: mysql2
  database: jira_test
