development: &development
 adapter: mysql2
 strict: false
 database: jira_tracker
 username: root
 host: localhost
 password:
 socket: /private/tmp/mysql.sock
production:
  adapter: pg
  database: jira_prod
